#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    ldiag1 = []
    ldiag2 = []
    for num in range(len(arr)):
        ldiag1.append(arr[num][num])
        ldiag2.append(arr[num][n-num-1])
        sd1=sum(ldiag1)
        sd2=sum(ldiag2)
    return abs(sd1-sd2)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
