#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    pos = 0
    neg = 0
    zero = 0
    for x in arr:
        if x > 0:
            pos += 1
        if x < 0:
            neg += 1
        else:
            zero += 1
        rpos = format(pos/n,'.6f')
        rneg= format(neg/n,'.6f')
        rzero = format(zero/n,'.6f')
    return rpos, rneg, rzero

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
