#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort2' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort2(n, arr): 
    for i in range(1,n):
        x = i
        while x>0 and arr[x-1]>arr[x]:
            arr[x],arr[x-1]=arr[x-1],arr[x]
            x-=1
        print(*arr)


if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)
