#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr): 
    a, x = arr[-1], -2
    while x>-n-1 and arr[x]>a:
            arr[x+1] = arr[x]
            x -=1
            print(' '.join(list(map(str,arr))))
    arr[x+1]=a
    print(' '.join(list(map(str,arr))))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
